server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
      gateway:
        routes:
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
              - Path=/catalog-service/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
              - Path=/order-service/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
logging:
  level:
    io.netty.resolver.dns: DEBUG
